name: unidata
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2025.12.2=h06a4308_0
  - freetype=2.13.3=h4a9f257_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jpeg=9f=h5ce9db8_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgomp=15.2.0=h4751f2c_7
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.5.1=hffd6297_1
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - ncurses=6.5=h7934f7d_0
  - numpy=1.19.5=py38h7820934_5
  - numpy-base=1.19.5=py38hfdd66db_5
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.18=hd6dcaed_0
  - pillow=10.4.0=py38h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.51.0=h2a70700_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - anyio==4.5.2
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.0.4
      - attrs==25.3.0
      - babel==2.17.0
      - backcall==0.2.0
      - backports-zoneinfo==0.2.1
      - beautifulsoup4==4.14.3
      - black==24.8.0
      - bleach==6.1.0
      - cachetools==5.5.2
      - ccimport==0.3.7
      - certifi==2025.11.12
      - cffi==1.17.1
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==46.0.3
      - cumm-cu111==0.2.9
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - descartes==1.1.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.14.0
      - fire==0.7.1
      - flake8==7.1.2
      - fonttools==4.57.0
      - fqdn==1.5.1
      - fsspec==2025.3.0
      - google-auth==2.43.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.1.0
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.4.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.7
      - lark==1.3.1
      - llvmlite==0.31.0
      - lyft-dataset-sdk==0.0.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.6.3
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.1.4
      - mmcv-full==1.4.0
      - mmdet==2.14.0
      - mmsegmentation==0.14.1
      - model-index==0.1.11
      - mypy-extensions==1.1.0
      - narwhals==1.42.1
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==2.2
      - ninja==1.13.0
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numba==0.48.0
      - nuscenes-devkit==1.1.9
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==1.4.4
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pathspec==0.12.1
      - pccm==0.3.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==6.5.0
      - pluggy==1.5.0
      - plyfile==1.0.3
      - portalocker==3.0.0
      - prettytable==3.11.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.52
      - protobuf==5.29.5
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.1
      - pycocotools==2.0.7
      - pycodestyle==2.12.1
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pyflakes==3.2.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytz==2023.4
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.35.1
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.4.2
      - rpds-py==0.20.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-image==0.19.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - send2trash==1.8.3
      - setuptools==60.2.0
      - shapely==2.0.7
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - spconv-cu111==2.1.25
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - terminado==0.18.1
      - terminaltables==3.1.10
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==1.0.22
      - tinycss2==1.2.1
      - tomli==2.3.0
      - torch==1.9.1+cu111
      - torchaudio==0.9.1
      - torchvision==0.10.1+cu111
      - tornado==6.4.2
      - tqdm==4.65.2
      - traitlets==5.14.3
      - typing-extensions==4.13.2
      - uri-template==1.3.0
      - urllib3==1.26.20
      - wcwidth==0.2.14
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.15
      - yapf==0.43.0
      - zipp==3.20.2
prefix: /home/kevin/anaconda3/envs/unidata
